'use client'

// =============================================================================
// WeeklyDigestCard — on-demand AI weekly digest, shown on the dashboard. The
// digest is generated by POST /api/assistant/digest (real LLM via the existing
// `chat` function + deterministic fallback). The card shows:
//   - empty state with a "Generate" button (no digest yet)
//   - AIAnswerSkeleton while the LLM call is pending
//   - weekSummary paragraph + highlights as stat chips + "View full digest"
//     button (opens DigestViewerDialog) once a digest exists
//   - a "Refresh" button in the header to regenerate at any time
// =============================================================================

import { useState } from 'react'
import {
  Sparkles,
  RefreshCw,
  Loader2,
  FileText,
  CalendarRange,
  TrendingUp,
} from 'lucide-react'

import {
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { AIAnswerSkeleton } from '@/components/common/skeletons'

import { useWeeklyDigest } from '@/hooks/use-queries'
import { formatRelative } from '@/lib/format'
import { DigestViewerDialog } from './digest-viewer-dialog'
import type { WeeklyDigest } from '@/app/api/assistant/digest/route'

// -----------------------------------------------------------------------------
// Highlight chip — compact stat tile reused in the card body.
// -----------------------------------------------------------------------------
function HighlightChip({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-lg border border-border/70 bg-muted/40 px-3 py-2">
      <div className="truncate text-[11px] uppercase tracking-wide text-muted-foreground">
        {label}
      </div>
      <div className="mt-0.5 text-lg font-semibold tabular-nums text-foreground">
        {value}
      </div>
    </div>
  )
}

// -----------------------------------------------------------------------------
// Empty state — no digest generated yet.
// -----------------------------------------------------------------------------
function EmptyDigestState({ onGenerate, pending }: { onGenerate: () => void; pending: boolean }) {
  return (
    <div className="flex flex-col items-start gap-3 rounded-lg border border-dashed border-border/70 bg-muted/30 p-4">
      <div className="flex h-9 w-9 items-center justify-center rounded-full bg-primary/10 text-primary">
        <CalendarRange className="h-5 w-5" />
      </div>
      <div className="space-y-1">
        <p className="text-sm font-medium text-foreground">
          Generate your weekly digest
        </p>
        <p className="text-sm text-muted-foreground">
          The AI will synthesize the last 7 days of mailbox activity into a
          concise summary with deadlines, action items, and recommendations.
        </p>
      </div>
      <Button size="sm" onClick={onGenerate} disabled={pending}>
        {pending ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Sparkles className="h-3.5 w-3.5" />}
        {pending ? 'Generating…' : 'Generate weekly digest'}
      </Button>
    </div>
  )
}

// -----------------------------------------------------------------------------
// Main card
// -----------------------------------------------------------------------------
export function WeeklyDigestCard({
  categoryColors = {},
}: {
  categoryColors?: Record<string, string>
}) {
  const mutation = useWeeklyDigest()
  const [dialogOpen, setDialogOpen] = useState(false)
  const digest: WeeklyDigest | undefined = mutation.data
  const isPending = mutation.isPending
  // While a refresh is pending AND we already have a digest, keep showing the
  // existing digest (don't swap to skeleton) so the UX feels continuous.
  const showSkeleton = isPending && !digest

  return (
    <>
      <Card className="gap-0 overflow-hidden">
        <CardHeader className="pb-3">
          <CardTitle className="flex items-center gap-2 text-base">
            <span className="flex h-7 w-7 items-center justify-center rounded-full bg-primary/10 text-primary">
              <Sparkles className="h-4 w-4" />
            </span>
            Weekly Digest
          </CardTitle>
          <CardDescription>
            AI-generated summary of your last 7 days
            {digest && (
              <span className="ml-1 tabular-nums">· updated {formatRelative(digest.generatedAt)}</span>
            )}
          </CardDescription>
          {digest && (
            <CardAction>
              <Button
                size="sm"
                variant="outline"
                onClick={() => mutation.mutate()}
                disabled={isPending}
              >
                {isPending ? (
                  <Loader2 className="h-3.5 w-3.5 animate-spin" />
                ) : (
                  <RefreshCw className="h-3.5 w-3.5" />
                )}
                {isPending ? 'Refreshing…' : 'Refresh'}
              </Button>
            </CardAction>
          )}
        </CardHeader>

        <CardContent className="space-y-4">
          {showSkeleton ? (
            <AIAnswerSkeleton />
          ) : digest ? (
            <>
              <p className="text-sm leading-relaxed text-foreground">
                {digest.weekSummary}
              </p>

              {digest.highlights.length > 0 && (
                <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
                  {digest.highlights.slice(0, 4).map((h, i) => (
                    <HighlightChip key={`${h.label}-${i}`} label={h.label} value={h.value} />
                  ))}
                </div>
              )}

              {/* Quick peek at secondary signal so the card isn't just text + chips. */}
              {(digest.keyDeadlines.length > 0 ||
                digest.recommendedActions.length > 0) && (
                <div className="grid gap-2 sm:grid-cols-2">
                  {digest.keyDeadlines.length > 0 && (
                    <div className="rounded-lg border border-border/60 bg-card px-3 py-2.5">
                      <div className="flex items-center gap-1.5 text-xs font-medium text-muted-foreground">
                        <CalendarRange className="h-3.5 w-3.5" />
                        Top deadline
                      </div>
                      <div className="mt-1 truncate text-sm font-medium text-foreground">
                        {digest.keyDeadlines[0]!.title}
                      </div>
                    </div>
                  )}
                  {digest.recommendedActions.length > 0 && (
                    <div className="rounded-lg border border-border/60 bg-card px-3 py-2.5">
                      <div className="flex items-center gap-1.5 text-xs font-medium text-muted-foreground">
                        <TrendingUp className="h-3.5 w-3.5" />
                        Next step
                      </div>
                      <div className="mt-1 truncate text-sm font-medium text-foreground">
                        {digest.recommendedActions[0]!.action}
                      </div>
                    </div>
                  )}
                </div>
              )}

              <div className="flex flex-wrap items-center gap-2 pt-1">
                <Button size="sm" variant="outline" onClick={() => setDialogOpen(true)}>
                  <FileText className="h-3.5 w-3.5" />
                  View full digest
                </Button>
                {!mutation.isPending && (
                  <span className="text-xs text-muted-foreground tabular-nums">
                    {digest.source === 'ai' ? 'Synthesized by AI' : 'Offline summary'}
                  </span>
                )}
              </div>
            </>
          ) : (
            <EmptyDigestState onGenerate={() => mutation.mutate()} pending={isPending} />
          )}
        </CardContent>
      </Card>

      <DigestViewerDialog
        open={dialogOpen}
        onOpenChange={setDialogOpen}
        digest={digest ?? null}
        categoryColors={categoryColors}
      />
    </>
  )
}
