'use client'

// SmartRepliesPanel — inline AI reply-suggestion panel shown in the email
// detail reading column. Renders 3 reply options (formal / brief /
// clarifying) generated by the real LLM (POST /api/emails/[id]/smart-replies).
// Lets the user draft a reply in the compose drawer with a single click.
//
// The mutation is owned by the parent (EmailDetailContent) so the toolbar
// button can trigger generation immediately on click. This panel is purely
// presentational: it renders loading / results / empty states based on the
// `data` and `isPending` props, and surfaces `onRefresh` / `onClose` callbacks.
//
// UX:
//  - First render (no data, not pending): hint + "Generate" button.
//  - Pending: AIAnswerSkeleton (matches the existing AI panel aesthetic).
//  - Success: 3 reply cards (tone badge via cat-*, subject, body, actions).
//  - Each reply has "Use this reply" (primary — opens compose pre-filled) and
//    "Copy" (ghost — copies the body to the clipboard).
//  - The header action becomes "Refresh" after the first generation so the
//    user can regenerate against the same (or updated) email.
//
// Design rules:
//  - Semantic Tailwind tokens only. No hardcoded hex/rgb. No indigo/blue.
//  - Tone badges use cat-* classes (cat-teal / cat-amber / cat-violet).
//  - All icons are statically imported from lucide-react (no lookup pattern).

import { useMemo } from 'react'
import { useUIStore } from '@/store/ui-store'
import { toast } from 'sonner'
import { AIAnswerSkeleton } from '@/components/common/skeletons'
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardAction } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Separator } from '@/components/ui/separator'
import { Tooltip, TooltipTrigger, TooltipContent } from '@/components/ui/tooltip'
import { cn } from '@/lib/utils'
import { formatRelative } from '@/lib/format'
import type { EmailDetail, Recipient } from '@/lib/types'
import type {
  SmartReply,
  SmartReplyTone,
  SmartRepliesResult,
} from '@/app/api/emails/[messageId]/smart-replies/route'
import {
  Sparkles,
  RefreshCw,
  Loader2,
  ClipboardCopy,
  Check,
  PencilLine,
  X,
} from 'lucide-react'

// ---------------------------------------------------------------------------
// Tone presentation
// ---------------------------------------------------------------------------

const TONE_CAT_CLASS: Record<SmartReplyTone, string> = {
  formal: 'cat-teal',
  brief: 'cat-amber',
  clarifying: 'cat-violet',
}

const TONE_LABEL: Record<SmartReplyTone, string> = {
  formal: 'Formal',
  brief: 'Brief',
  clarifying: 'Clarifying',
}

const TONE_HINT: Record<SmartReplyTone, string> = {
  formal: 'Acknowledges and lays out next steps',
  brief: 'Short acknowledgment',
  clarifying: 'Asks for more information',
}

// ---------------------------------------------------------------------------
// Panel
// ---------------------------------------------------------------------------

export function SmartRepliesPanel({
  email,
  data,
  isPending,
  onRefresh,
  onClose,
}: {
  email: EmailDetail
  data: SmartRepliesResult | undefined
  isPending: boolean
  onRefresh: () => void
  onClose?: () => void
}) {
  const setComposeOpen = useUIStore((s) => s.setComposeOpen)
  const setComposePrefill = useUIStore((s) => s.setComposePrefill)

  const replies = data?.replies ?? []
  const hasData = !!data && replies.length > 0

  // Build the recipient the reply should be addressed to. Reply-To: the
  // original sender. (A real Gmail client would honor Reply-To headers; the
  // institutional corpus doesn't define them, so fromEmail is correct.)
  const replyTo: Recipient[] = useMemo(
    () => [{ email: email.fromEmail, name: email.fromName ?? undefined }],
    [email.fromEmail, email.fromName],
  )

  const handleUseReply = (reply: SmartReply) => {
    setComposePrefill({
      to: replyTo,
      subject: reply.subject,
      body: reply.body,
    })
    setComposeOpen(true)
    toast.info('Reply drafted — opening compose', {
      description: `${TONE_LABEL[reply.tone]} reply pre-filled.`,
    })
  }

  const handleCopy = async (reply: SmartReply) => {
    try {
      await navigator.clipboard.writeText(reply.body)
      toast.success('Copied reply body', {
        description: `${TONE_LABEL[reply.tone]} · ${reply.subject}`,
      })
    } catch {
      // Fallback for browsers without async clipboard API.
      const ta = document.createElement('textarea')
      ta.value = reply.body
      ta.style.position = 'fixed'
      ta.style.opacity = '0'
      document.body.appendChild(ta)
      ta.select()
      try {
        document.execCommand('copy')
        toast.success('Copied reply body')
      } catch {
        toast.error('Could not copy', { description: 'Clipboard access denied.' })
      }
      document.body.removeChild(ta)
    }
  }

  return (
    <Card className="gap-0 overflow-hidden py-0">
      <CardHeader className="gap-1 border-b bg-muted/30 px-4 py-3">
        <div className="flex items-start gap-2">
          <span
            className="mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-primary/10 text-primary"
            aria-hidden
          >
            <Sparkles className="h-4 w-4" />
          </span>
          <div className="min-w-0 flex-1">
            <CardTitle className="text-sm">Smart Replies</CardTitle>
            <CardDescription className="text-xs">
              AI-generated reply suggestions
              {data && (
                <span className="ml-1 opacity-80">
                  · updated {formatRelative(data.generatedAt)}
                  {data.source === 'fallback' && ' · offline'}
                </span>
              )}
            </CardDescription>
          </div>
        </div>
        <CardAction className="flex items-center gap-1">
          <Button
            size="sm"
            variant={hasData ? 'outline' : 'default'}
            onClick={onRefresh}
            disabled={isPending}
            className="h-7 gap-1.5 px-2 text-xs"
          >
            {isPending ? (
              <Loader2 className="h-3.5 w-3.5 animate-spin" />
            ) : hasData ? (
              <RefreshCw className="h-3.5 w-3.5" />
            ) : (
              <Sparkles className="h-3.5 w-3.5" />
            )}
            <span className="hidden sm:inline">
              {isPending ? 'Generating…' : hasData ? 'Refresh' : 'Generate'}
            </span>
          </Button>
          {onClose && (
            <Tooltip>
              <TooltipTrigger asChild>
                <Button
                  size="icon"
                  variant="ghost"
                  onClick={onClose}
                  className="h-7 w-7"
                  aria-label="Close smart replies"
                >
                  <X className="h-3.5 w-3.5" />
                </Button>
              </TooltipTrigger>
              <TooltipContent side="bottom">Close</TooltipContent>
            </Tooltip>
          )}
        </CardAction>
      </CardHeader>

      <CardContent className="px-4 py-3">
        {isPending ? (
          <AIAnswerSkeleton />
        ) : hasData ? (
          <ul className="flex flex-col gap-3">
            {replies.map((reply, idx) => (
              <li key={`${reply.tone}-${idx}`}>
                <ReplyCard
                  reply={reply}
                  onUse={() => handleUseReply(reply)}
                  onCopy={() => handleCopy(reply)}
                />
                {idx < replies.length - 1 && <Separator className="mt-3" />}
              </li>
            ))}
          </ul>
        ) : (
          <div className="flex flex-col items-start gap-2 py-2 text-sm text-muted-foreground">
            <p>
              Generate three ready-to-send reply options for this email — formal,
              brief, and clarifying — then draft your favourite in the compose
              drawer with one click.
            </p>
            <p className="text-xs">
              Powered by the real LLM. Falls back to deterministic suggestions if
              the model is unavailable.
            </p>
          </div>
        )}
      </CardContent>
    </Card>
  )
}

// ---------------------------------------------------------------------------
// Single reply card — tone badge + subject + body + actions
// ---------------------------------------------------------------------------

function ReplyCard({
  reply,
  onUse,
  onCopy,
}: {
  reply: SmartReply
  onUse: () => void
  onCopy: () => void
}) {
  const catClass = TONE_CAT_CLASS[reply.tone]
  return (
    <div className="flex flex-col gap-2 pt-1 first:pt-0">
      <div className="flex flex-wrap items-center gap-2">
        <span
          className={cn(
            'inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-[11px] font-medium cat-bg-soft cat-text cat-border-soft',
            catClass,
          )}
        >
          <span className={cn('h-1.5 w-1.5 rounded-full cat-dot', catClass)} aria-hidden />
          {TONE_LABEL[reply.tone]}
        </span>
        <span className="text-[11px] text-muted-foreground">{TONE_HINT[reply.tone]}</span>
      </div>

      <p className="truncate text-sm font-semibold leading-snug" title={reply.subject}>
        {reply.subject}
      </p>

      <div className="rounded-lg border bg-muted/40 p-3">
        <p className="whitespace-pre-wrap text-[13px] leading-6 text-foreground/90">
          {reply.body}
        </p>
      </div>

      <div className="flex flex-wrap items-center gap-2">
        <Button size="sm" onClick={onUse} className="h-7 gap-1.5 px-2 text-xs">
          <PencilLine className="h-3.5 w-3.5" />
          Use this reply
        </Button>
        <Button
          size="sm"
          variant="ghost"
          onClick={onCopy}
          className="h-7 gap-1.5 px-2 text-xs text-muted-foreground hover:text-foreground"
        >
          <ClipboardCopy className="h-3.5 w-3.5" />
          Copy
        </Button>
        <Badge variant="outline" className="ml-auto px-1.5 py-0 text-[10px] text-muted-foreground">
          <Check className="h-3 w-3" />
          ready to send
        </Badge>
      </div>
    </div>
  )
}
