from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'User',
    'AccountConnection',
    'SyncState',
    'Thread',
    'Sender',
    'Category',
    'Email',
    'EmailAttachment',
    'CategoryMembership',
    'ClassificationResult',
    'Rule',
    'RuleVersion',
    'UserOverride',
    'Deadline',
    'ActionItem',
    'Notification',
    'NotificationPreference',
    'AssistantConversation',
    'AssistantMessage',
    'AssistantAction',
    'AuditEvent',
    'Draft',
    'SavedSearch',
    'EmailTemplate',
    'Conversation',
    'EmailRelationship',
    'ConversationOverride',
    'ScanConfiguration',
    'ScanJob',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'User': {
        'accounts': 'AccountConnection',
        'assistantConversations': 'AssistantConversation',
        'auditEvents': 'AuditEvent',
    },
    'AccountConnection': {
        'user': 'User',
        'syncState': 'SyncState',
        'threads': 'Thread',
        'senders': 'Sender',
        'categories': 'Category',
        'emails': 'Email',
        'rules': 'Rule',
        'notifications': 'Notification',
        'deadlines': 'Deadline',
        'actionItems': 'ActionItem',
        'assistantConvs': 'AssistantConversation',
        'auditEvents': 'AuditEvent',
        'assistantActions': 'AssistantAction',
        'notificationPrefs': 'NotificationPreference',
    },
    'SyncState': {
        'account': 'AccountConnection',
    },
    'Thread': {
        'account': 'AccountConnection',
        'emails': 'Email',
        'conversation': 'Conversation',
    },
    'Sender': {
        'account': 'AccountConnection',
        'emails': 'Email',
    },
    'Category': {
        'account': 'AccountConnection',
        'memberships': 'CategoryMembership',
        'notifications': 'Notification',
        'deadlines': 'Deadline',
        'notificationPrefs': 'NotificationPreference',
    },
    'Email': {
        'account': 'AccountConnection',
        'thread': 'Thread',
        'sender': 'Sender',
        'attachments': 'EmailAttachment',
        'memberships': 'CategoryMembership',
        'deadlines': 'Deadline',
        'actionItems': 'ActionItem',
        'classifications': 'ClassificationResult',
        'notifications': 'Notification',
    },
    'EmailAttachment': {
        'email': 'Email',
    },
    'CategoryMembership': {
        'email': 'Email',
        'category': 'Category',
    },
    'ClassificationResult': {
        'email': 'Email',
    },
    'Rule': {
        'account': 'AccountConnection',
        'versions': 'RuleVersion',
    },
    'RuleVersion': {
        'rule': 'Rule',
    },
    'UserOverride': {
    },
    'Deadline': {
        'account': 'AccountConnection',
        'email': 'Email',
        'category': 'Category',
    },
    'ActionItem': {
        'account': 'AccountConnection',
        'email': 'Email',
    },
    'Notification': {
        'account': 'AccountConnection',
        'email': 'Email',
        'category': 'Category',
    },
    'NotificationPreference': {
        'account': 'AccountConnection',
        'category': 'Category',
    },
    'AssistantConversation': {
        'user': 'User',
        'account': 'AccountConnection',
        'messages': 'AssistantMessage',
        'actions': 'AssistantAction',
    },
    'AssistantMessage': {
        'conversation': 'AssistantConversation',
    },
    'AssistantAction': {
        'conversation': 'AssistantConversation',
        'account': 'AccountConnection',
    },
    'AuditEvent': {
        'user': 'User',
        'account': 'AccountConnection',
    },
    'Draft': {
    },
    'SavedSearch': {
    },
    'EmailTemplate': {
    },
    'Conversation': {
        'threads': 'Thread',
        'overrides': 'ConversationOverride',
    },
    'EmailRelationship': {
    },
    'ConversationOverride': {
        'conversation': 'Conversation',
    },
    'ScanConfiguration': {
    },
    'ScanJob': {
    },
}

# fmt: on